apiVersion: apps/v1
kind: Deployment

metadata:
  name: churn-flask-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: churn-flask-app

  template:
    metadata:
      labels:
        app: churn-flask-app

    spec:
      containers:
        - name: churn-flask-container
          image: vel23/mlops-jenkins-churn-prediction:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
